printWidth: 150 # Максимальная длина строки
tabWidth: 2 # Размер отступа
singleQuote: true # Использовать одинарные кавычки
trailingComma: all # Добавлять запятые в конце списков
arrowParens: always # Всегда использовать скобки в стрелочных функциях
semi: false # Не добавлять точку с запятой в конце строк
overrides:
  - files: '*.ts' # Настройки для TypeScript файлов
    options:
      parser: typescript # Использовать TypeScript парсер
